schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.65.0"
    hash = "sha256-RAddw1zhWSmE/xpcoqCcCY2s+fzj9oQq27PAtxjJVBo="
  [mod."cloud.google.com/go/bigquery"]
    version = "v1.8.0"
    hash = "sha256-gd0qQ9n3vPAi+uj/rbTKpswQR/EKKXF7xepyvnvJx1w="
  [mod."cloud.google.com/go/datastore"]
    version = "v1.1.0"
    hash = "sha256-wyOuic/vp33s1QiybElwERALQwPrn8gFHDAdlTBcv1Q="
  [mod."cloud.google.com/go/pubsub"]
    version = "v1.3.1"
    hash = "sha256-q1bn0VzdKso3+YBWnfIcCXEYTvY3K6gYsVLUB0wdOyc="
  [mod."cloud.google.com/go/storage"]
    version = "v1.10.0"
    hash = "sha256-8I1IKhHdIC4Gxhi2IfdTU6UXKObg2ZsZuDR6hM5t51k="
  [mod."dmitri.shuralyov.com/gpu/mtl"]
    version = "v0.0.0-20190408044501-666a987793e9"
    hash = "sha256-H+xcbVdCNDahWZPgwk4k+XxnM73g0hwaFY7x+OAATcc="
  [mod."github.com/BurntSushi/toml"]
    version = "v0.3.1"
    hash = "sha256-Rqak1dE/Aj/+Kx1/pl3Hifgt+Q3OzuZ5fJR+/x3nTbo="
  [mod."github.com/BurntSushi/xgb"]
    version = "v0.0.0-20160522181843-27f122750802"
    hash = "sha256-ck+gNOSXNYy/ji6mpSX3OTHgCDm2nww+3ZKu4lAXl6I="
  [mod."github.com/antihax/optional"]
    version = "v1.0.0"
    hash = "sha256-QGaiZUrNRq6obhRvPiG034d3EmUBCMMyKrnjROhGoMc="
  [mod."github.com/census-instrumentation/opencensus-proto"]
    version = "v0.2.1"
    hash = "sha256-3RWTfGGuKbkrOQ91ociOgp9igGvU/FAv3NAidPVoYP8="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.1"
    hash = "sha256-cF+sDnnTZ1xRwjsy08SVSV/JoZalwY+dg0Zkghy6BNw="
  [mod."github.com/chzyer/logex"]
    version = "v1.1.10"
    hash = "sha256-BNOaV/CFAqOymWW3R2m1sCikdCwFZM/pVkylzoeU6yI="
  [mod."github.com/chzyer/readline"]
    version = "v0.0.0-20180603132655-2972be24d48e"
    hash = "sha256-2Uj5LGpHEbLQG3d/7z9AL8DknUBZyoTAMs4j+VVDmIA="
  [mod."github.com/chzyer/test"]
    version = "v0.0.0-20180213035817-a1ea475d72b1"
    hash = "sha256-U0irpUSqegh7Nzg1ErPuyjESOcIXXOWf7ikKMbES2mY="
  [mod."github.com/client9/misspell"]
    version = "v0.3.4"
    hash = "sha256-MIKnt4va/nPl+5cCgOvCyRGIORTnguieQhlj8ery4BU="
  [mod."github.com/cncf/udpa/go"]
    version = "v0.0.0-20210930031921-04548b0d99d4"
    hash = "sha256-3E8BNhFNIdSJg92cUmfB2fAUawpcQPQxtSDO8S5h7Is="
  [mod."github.com/cncf/xds/go"]
    version = "v0.0.0-20211011173535-cb28da3451f1"
    hash = "sha256-Vn9KOztHYqlX4zO+MZ28NFYz7BpdZibKhUD3gAN/igo="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.0"
    hash = "sha256-zNSuzjr5n7zhK8VOciSigLMfbnHbmyzsWdTcMlV1kjQ="
  [mod."github.com/envoyproxy/go-control-plane"]
    version = "v0.10.2-0.20220325020618-49ff273808a1"
    hash = "sha256-AKavO3tfcwHcax33tBhF4id7kKkNeqb6suCJx16ELsQ="
  [mod."github.com/envoyproxy/protoc-gen-validate"]
    version = "v0.1.0"
    hash = "sha256-2htufg3hdOHfbDVI5wFpsuaiDIhH6O1taUGJMdVbjlQ="
  [mod."github.com/ghodss/yaml"]
    version = "v1.0.0"
    hash = "sha256-D+2i+EwF2YptR0m/OG4WIVVLL7tUC7XvgRQef2usfGo="
  [mod."github.com/go-gl/glfw"]
    version = "v0.0.0-20190409004039-e6da0acd62b1"
    hash = "sha256-tqPStzM1xOuEWqAv4pBbzB+lNIxEqqyCCP0wWCbrlyY="
  [mod."github.com/go-gl/glfw/v3.3/glfw"]
    version = "v0.0.0-20200222043503-6f7a984d4dc4"
    hash = "sha256-6BfEsip1tEBelFTsKVtn2okCTb+0UsqEdIljg+PIjiE="
  [mod."github.com/golang/glog"]
    version = "v1.0.0"
    hash = "sha256-bglITqRgzi52zc6FoYYnfCvrjFWV4RVOacPCnbEBom4="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20200121045136-8c9f03a8e57e"
    hash = "sha256-0E3bzqOQk4xolVEGm0GXZ6tUpgCWF7DolyyKkdPJUm4="
  [mod."github.com/golang/mock"]
    version = "v1.4.4"
    hash = "sha256-13sT+TtOnOcjKXfrLwbLtlc1YrqMkY++R0plBl2aFAU="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/btree"]
    version = "v1.0.0"
    hash = "sha256-5gr0RMnlvrzCke3kwpkf92WvW3x5nnKZesoulyoYRC0="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.8"
    hash = "sha256-8zkIo+Sr1NXMnj3PNmvjX2sZKnAKWXOFvmnX7D9bwxQ="
  [mod."github.com/google/martian"]
    version = "v2.1.0+incompatible"
    hash = "sha256-N3tPu89U5MQqmtFIqSEfqEXNgnHf883TAmXKvA2N8KQ="
  [mod."github.com/google/martian/v3"]
    version = "v3.0.0"
    hash = "sha256-1Y2aQ6Tab/bAmzo5XtR1//LNb4kJR2qZRtoAZSjR+1k="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20200708004538-1a94d8640e99"
    hash = "sha256-zLjRAd8Bt2o0q9ujgyypYUCUwnrCCSEebqj2q1/Qzws="
  [mod."github.com/google/renameio"]
    version = "v0.1.0"
    hash = "sha256-XQ5yI+LMfFQuK7+T3Xx5jiaRP7GmiQSsPkFmm1TpIs4="
  [mod."github.com/google/uuid"]
    version = "v1.1.2"
    hash = "sha256-DXttjObhEiMn5/OH+mYkJU6u03Gwsx5t08lTsIFyd+U="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.0.5"
    hash = "sha256-2ibpBbDxLVeYHd8gdszHb3w8rgKrChbUNlkaxW9lIhU="
  [mod."github.com/grpc-ecosystem/grpc-gateway"]
    version = "v1.16.0"
    hash = "sha256-wLymGic7wZ6fSiBYDAaGqnQ9Ste1fUWeqXeolZXCHvI="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v0.5.1"
    hash = "sha256-/tr/EXgTmXPqrrx6kdMPMfWSC6GBdCPlX8GEuRk4yI0="
  [mod."github.com/ianlancetaylor/demangle"]
    version = "v0.0.0-20181102032728-5e5cf60278f6"
    hash = "sha256-5cS82VAt2PtDlx18XzvNwhp7zk/fryC9HCzdyEKYEro="
  [mod."github.com/jstemmer/go-junit-report"]
    version = "v0.9.1"
    hash = "sha256-fK6zLXQU8y+h+SqyeCUldA5OFPA/j0Wlbizk6AG60c4="
  [mod."github.com/kisielk/gotool"]
    version = "v1.0.0"
    hash = "sha256-lsdQkue8gFz754PGqczUnvGiCQq87SruQtdrDdQVTpE="
  [mod."github.com/kr/pretty"]
    version = "v0.1.0"
    hash = "sha256-Fx+TaNrxW0VfzonT2jnd5MU09RRz7GJZkqAtJR6/pKI="
  [mod."github.com/kr/pty"]
    version = "v1.1.1"
    hash = "sha256-AVeS+ivwNzIrgWQaLtsmO2f2MYGpxIVqdac/EzaYI1Q="
  [mod."github.com/kr/text"]
    version = "v0.1.0"
    hash = "sha256-QT65kTrNypS5GPWGvgnCpGLPlVbQAL4IYvuqAKhepb4="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_model"]
    version = "v0.0.0-20190812154241-14fe0d1b01d4"
    hash = "sha256-oJSU4o77UVps0e2SJUDz6enypNipZPDdZmn0tbKZtX0="
  [mod."github.com/rogpeppe/fastuuid"]
    version = "v1.2.0"
    hash = "sha256-yDnHsLw8KF4zfbJska1igIo4IbVpGDq+vH3+YV5jCgk="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.3.0"
    hash = "sha256-JgiasZeXDy10syy7wmXtqRffDY7CJ1o5VNY+FmmAjVU="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.0"
    hash = "sha256-az0Vd4MG3JXfaYbj0Q6AOmNkrXgmXDeQm8+BBiDXmdA="
  [mod."github.com/stretchr/testify"]
    version = "v1.7.0"
    hash = "sha256-t1I9uCrn9vSUu/z5IZuNyGShmbOcJ6UGc2f75ZBrHzE="
  [mod."github.com/yuin/goldmark"]
    version = "v1.1.32"
    hash = "sha256-RR1vIZ9WcAo5h/EEQepHvtlE7B3dxA7OLnb7YQ32KQ4="
  [mod."go.opencensus.io"]
    version = "v0.22.4"
    hash = "sha256-DFTy7YYUxHTtc77ts+7cHvvMUuv3nk/iUoow6JYKp6Q="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v0.7.0"
    hash = "sha256-B6Z7QlMn8wI7MCggPzXUsl5JOrhjv/w+tlnT6d7IHo0="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20200622213623-75b288015ac9"
    hash = "sha256-QvFbJEm3gXs2NtaaREbkbAtdHpU4fqX+0C0EvTezdKM="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20200224162631-6cc2880d07d6"
    hash = "sha256-bhrVk10F9h0g3uRn+rJEA66KqUNy6fG2H56T04KfXPk="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20190802002840-cff245a6509b"
    hash = "sha256-BP2l1VUXd5afv4fsZ9g6WYy6zEPY782ZAsMrFSe1P0I="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20200302205851-738671d3881b"
    hash = "sha256-LNkJ9QCzsDgFjrLI+hYNISu9jrsu9tX9tFKm4i/5cUo="
  [mod."golang.org/x/mobile"]
    version = "v0.0.0-20190719004257-d2bd2a29d028"
    hash = "sha256-At0uE2mTr/GHCyF4U8Z+AiU2jlvBVQuX25tooo2ll6M="
  [mod."golang.org/x/mod"]
    version = "v0.3.0"
    hash = "sha256-c+KKzeDUDxrKIx8un1DpETlTK+DmHP+zUjRZrgs0ejo="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220127200216-cd36cc0744dd"
    hash = "sha256-MJiGGZjsWS3Egd/9yuO2PDB8lMjuhuHT6RMCCtdrbb4="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20220622183110-fd043fe589d2"
    hash = "sha256-VLffpTpx3DlUzXB8mKiJfFzm4ZmgnLSUuLB5Ir0WQUg="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20200625203802-6e8e738ad208"
    hash = "sha256-qXsBjPaADZWo41J4CEOOhij6ODryOGdcK7S0r+8Rc6s="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20211216021012-1d35b9e2eb4e"
    hash = "sha256-q9nSttSlJMZ9rggzT0YwuWWdWrqtpU08eOCt3mcM27Y="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210927222741-03fcf44c2211"
    hash = "sha256-DsX2xay7Y/0/bikp4vU8ArF0B6KHyqEc37PwgvmjhSs="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20191024005414-555d28b269f0"
    hash = "sha256-mUBTPUGSwdV1+u1Xp8L2ecfR/EDTD/O04xMM8D0lFOY="
  [mod."golang.org/x/tools"]
    version = "v0.0.0-20200825202427-b303f430e36d"
    hash = "sha256-iOaGwZteOHJviBWtjkz4xVi76/IK9p0sS2KTWYC49DM="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/api"]
    version = "v0.30.0"
    hash = "sha256-o/LIHY/jZ/1j8lWvqOXZ79Q3p6KcLdXXXNy69035eh4="
  [mod."google.golang.org/appengine"]
    version = "v1.6.6"
    hash = "sha256-nZnEfsXy3mgzRnlyWGHJKqsosvnAQFkhVszw3DSFe6Y="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20220624142145-8cd45d7dbd1f"
    hash = "sha256-4vtHoY3I9zBpJgSiMPNQR78yfAoa9x+Hstr6I6WLXV4="
  [mod."google.golang.org/grpc"]
    version = "v1.47.0"
    hash = "sha256-bollpfZmc/+8Ga7cFKp4gKX83wTKo/lw7vBW5SV3e9o="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.0"
    hash = "sha256-p1cVM3OeEErh1WeNRAg4n3zYm/0qPTPmIiWNjRmJiMQ="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20180628173108-788fd7840127"
    hash = "sha256-KsRJNTprd1UijnJusbHwQGM7Bdm45Jt/QL+cIUGNa2w="
  [mod."gopkg.in/errgo.v2"]
    version = "v2.1.0"
    hash = "sha256-Ir/MuxQFxvVJEciovGOZbM8ZfKJ/AYotPwYfH2FctRg="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.3"
    hash = "sha256-Peeu/2J0+p0YQOZD0UW6k9Twv3a+C25r3nM+gII/WlA="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."honnef.co/go/tools"]
    version = "v0.0.1-2020.1.4"
    hash = "sha256-HUAzW7uFbMQpIYwsd6BzSy2jaO+3ymfjwjoVeEnNFIA="
  [mod."rsc.io/binaryregexp"]
    version = "v0.2.0"
    hash = "sha256-izALTmzybQe67BNXliqQ3xCEOo+b6o8C4YoX5H0FWc0="
  [mod."rsc.io/quote/v3"]
    version = "v3.1.0"
    hash = "sha256-sF7lOq/bInDPtLI+j610WJRAQ09Cxc5lmPzzytuE6DI="
  [mod."rsc.io/sampler"]
    version = "v1.3.0"
    hash = "sha256-UPbUO3GOGn6/fz1EBEYONBX45V6bzQKQv6CoZb2Y3S8="
